# Generated by Django 4.0.5 on 2022-07-09 02:32

from django.db import migrations, models

PARTS = ["등", "어깨", "팔", "가슴", "복근", "하체", "유산소"]


def create_parts(apps, schema_editor):
    part_model = apps.get_model('workout', 'Part')
    for part in PARTS:
        part_model.objects.create(name=part)


class Migration(migrations.Migration):
    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.RunPython(create_parts, reverse_code=migrations.RunPython.noop),
    ]
