# Generated by Django 4.0.5 on 2022-08-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_add_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
