# Generated by Django 4.0.5 on 2022-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='code',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
