# Generated by Django 4.0.5 on 2022-08-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0004_alter_part_name_alter_workout_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
